<?php

namespace Modules\Materiais\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Materiais\App\Models\Material;
use Illuminate\Support\Facades\DB;

class MateriaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Limpar materiais existentes (opcional - comentar em produção)
        // Material::truncate();

        $materiais = [
            // ========== ELÉTRICA ==========

            // Relés Fotoeletrônicos
            [
                'nome' => 'Relé Fotoeletrônico 127V 1000W',
                'categoria' => 'rele_fotoeletronico',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 10,
                'quantidade_minima' => 5,
                'valor_unitario' => 45.90,
                'fornecedor' => 'Schneider Electric',
                'localizacao_estoque' => 'Prateleira E1',
                'campos_especificos' => [
                    'tensao' => '127V',
                    'potencia' => '1000',
                    'tipo_instalacao' => 'Parede',
                    'marca' => 'Schneider',
                    'modelo' => 'RE-1000',
                    'certificacao' => 'INMETRO',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Relé Fotoeletrônico 220V 2000W',
                'categoria' => 'rele_fotoeletronico',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 8,
                'quantidade_minima' => 4,
                'valor_unitario' => 68.50,
                'fornecedor' => 'WEG',
                'localizacao_estoque' => 'Prateleira E1',
                'campos_especificos' => [
                    'tensao' => '220V',
                    'potencia' => '2000',
                    'tipo_instalacao' => 'Poste',
                    'marca' => 'WEG',
                    'modelo' => 'WRE-2000',
                    'certificacao' => 'INMETRO',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Relé Fotoeletrônico 127V 500W',
                'categoria' => 'rele_fotoeletronico',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 15,
                'quantidade_minima' => 8,
                'valor_unitario' => 35.90,
                'fornecedor' => 'Schneider Electric',
                'localizacao_estoque' => 'Prateleira E1',
                'campos_especificos' => [
                    'tensao' => '127V',
                    'potencia' => '500',
                    'tipo_instalacao' => 'Parede',
                    'marca' => 'Schneider',
                    'modelo' => 'RE-500',
                    'certificacao' => 'INMETRO',
                ],
                'ativo' => true,
            ],

            // Fios Elétricos
            [
                'nome' => 'Fio Elétrico 2.5mm² Vermelho',
                'categoria' => 'fios_eletricos',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 500,
                'quantidade_minima' => 200,
                'valor_unitario' => 2.85,
                'fornecedor' => 'Prysmian',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'bitola' => '2.5',
                    'tensao' => '127V/220V',
                    'cor' => 'Vermelho',
                    'material' => 'Cobre',
                    'marca' => 'Prysmian',
                    'norma_tecnica' => 'ABNT NBR 7286',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Fio Elétrico 2.5mm² Preto',
                'categoria' => 'fios_eletricos',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 500,
                'quantidade_minima' => 200,
                'valor_unitario' => 2.85,
                'fornecedor' => 'Prysmian',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'bitola' => '2.5',
                    'tensao' => '127V/220V',
                    'cor' => 'Preto',
                    'material' => 'Cobre',
                    'marca' => 'Prysmian',
                    'norma_tecnica' => 'ABNT NBR 7286',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Fio Elétrico 2.5mm² Verde/Amarelo',
                'categoria' => 'fios_eletricos',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 300,
                'quantidade_minima' => 150,
                'valor_unitario' => 2.85,
                'fornecedor' => 'Prysmian',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'bitola' => '2.5',
                    'tensao' => '127V/220V',
                    'cor' => 'Verde',
                    'material' => 'Cobre',
                    'marca' => 'Prysmian',
                    'norma_tecnica' => 'ABNT NBR 7286',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Fio Elétrico 4.0mm² Vermelho',
                'categoria' => 'fios_eletricos',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 400,
                'quantidade_minima' => 200,
                'valor_unitario' => 4.20,
                'fornecedor' => 'Nexans',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'bitola' => '4.0',
                    'tensao' => '127V/220V',
                    'cor' => 'Vermelho',
                    'material' => 'Cobre',
                    'marca' => 'Nexans',
                    'norma_tecnica' => 'ABNT NBR 7286',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Fio Elétrico 6.0mm² Vermelho',
                'categoria' => 'fios_eletricos',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 300,
                'quantidade_minima' => 150,
                'valor_unitario' => 6.50,
                'fornecedor' => 'Prysmian',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'bitola' => '6.0',
                    'tensao' => '127V/220V',
                    'cor' => 'Vermelho',
                    'material' => 'Cobre',
                    'marca' => 'Prysmian',
                    'norma_tecnica' => 'ABNT NBR 7286',
                ],
                'ativo' => true,
            ],

            // Cabos Elétricos
            [
                'nome' => 'Cabo Elétrico 10mm² 3 Condutores',
                'categoria' => 'cabos_eletricos',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 200,
                'quantidade_minima' => 100,
                'valor_unitario' => 18.90,
                'fornecedor' => 'Prysmian',
                'localizacao_estoque' => 'Prateleira C1',
                'campos_especificos' => [
                    'bitola' => '10.0',
                    'tensao' => '380V',
                    'material' => 'Cobre',
                    'marca' => 'Prysmian',
                    'norma_tecnica' => 'ABNT NBR 7286',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Cabo Elétrico 16mm² 3 Condutores',
                'categoria' => 'cabos_eletricos',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 150,
                'quantidade_minima' => 80,
                'valor_unitario' => 28.50,
                'fornecedor' => 'Nexans',
                'localizacao_estoque' => 'Prateleira C1',
                'campos_especificos' => [
                    'bitola' => '16.0',
                    'tensao' => '380V',
                    'material' => 'Cobre',
                    'marca' => 'Nexans',
                    'norma_tecnica' => 'ABNT NBR 7286',
                ],
                'ativo' => true,
            ],

            // Disjuntores
            [
                'nome' => 'Disjuntor Monopolar 10A 127V',
                'categoria' => 'disjuntores',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 25,
                'quantidade_minima' => 15,
                'valor_unitario' => 28.90,
                'fornecedor' => 'Schneider Electric',
                'localizacao_estoque' => 'Prateleira D1',
                'campos_especificos' => [
                    'tensao' => '127V',
                    'corrente' => '10',
                    'tipo' => 'Monopolar',
                    'marca' => 'Schneider',
                    'modelo' => 'DPN-10',
                    'certificacao' => 'INMETRO',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Disjuntor Monopolar 20A 127V',
                'categoria' => 'disjuntores',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 20,
                'quantidade_minima' => 12,
                'valor_unitario' => 32.50,
                'fornecedor' => 'Schneider Electric',
                'localizacao_estoque' => 'Prateleira D1',
                'campos_especificos' => [
                    'tensao' => '127V',
                    'corrente' => '20',
                    'tipo' => 'Monopolar',
                    'marca' => 'Schneider',
                    'modelo' => 'DPN-20',
                    'certificacao' => 'INMETRO',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Disjuntor Bipolar 20A 220V',
                'categoria' => 'disjuntores',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 18,
                'quantidade_minima' => 10,
                'valor_unitario' => 45.90,
                'fornecedor' => 'WEG',
                'localizacao_estoque' => 'Prateleira D1',
                'campos_especificos' => [
                    'tensao' => '220V',
                    'corrente' => '20',
                    'tipo' => 'Bipolar',
                    'marca' => 'WEG',
                    'modelo' => 'WBP-20',
                    'certificacao' => 'INMETRO',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Disjuntor DR 25A 220V',
                'categoria' => 'disjuntores',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 12,
                'quantidade_minima' => 8,
                'valor_unitario' => 125.00,
                'fornecedor' => 'Schneider Electric',
                'localizacao_estoque' => 'Prateleira D1',
                'campos_especificos' => [
                    'tensao' => '220V',
                    'corrente' => '25',
                    'tipo' => 'DR (Diferencial Residual)',
                    'marca' => 'Schneider',
                    'modelo' => 'DR-25',
                    'certificacao' => 'INMETRO',
                ],
                'ativo' => true,
            ],

            // Tomadas e Interruptores
            [
                'nome' => 'Tomada 2P+T 10A 127V Branca',
                'categoria' => 'tomadas_interruptores',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 50,
                'quantidade_minima' => 30,
                'valor_unitario' => 8.90,
                'fornecedor' => 'Schneider Electric',
                'localizacao_estoque' => 'Prateleira T1',
                'campos_especificos' => [
                    'tipo' => 'Tomada',
                    'tensao' => '127V',
                    'cor' => 'Branco',
                    'marca' => 'Schneider',
                    'modelo' => 'TOM-127',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Interruptor Simples 10A 127V Branco',
                'categoria' => 'tomadas_interruptores',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 45,
                'quantidade_minima' => 25,
                'valor_unitario' => 6.50,
                'fornecedor' => 'WEG',
                'localizacao_estoque' => 'Prateleira T1',
                'campos_especificos' => [
                    'tipo' => 'Interruptor',
                    'tensao' => '127V',
                    'cor' => 'Branco',
                    'marca' => 'WEG',
                    'modelo' => 'INT-127',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Interruptor Paralelo 10A 127V Branco',
                'categoria' => 'tomadas_interruptores',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 30,
                'quantidade_minima' => 20,
                'valor_unitario' => 12.90,
                'fornecedor' => 'Schneider Electric',
                'localizacao_estoque' => 'Prateleira T1',
                'campos_especificos' => [
                    'tipo' => 'Interruptor Paralelo',
                    'tensao' => '127V',
                    'cor' => 'Branco',
                    'marca' => 'Schneider',
                    'modelo' => 'INT-PAR-127',
                ],
                'ativo' => true,
            ],

            // Lâmpadas
            [
                'nome' => 'Lâmpada LED 20W 127V Branca Fria',
                'categoria' => 'lampadas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 50,
                'quantidade_minima' => 30,
                'valor_unitario' => 12.90,
                'fornecedor' => 'Philips',
                'localizacao_estoque' => 'Prateleira L1',
                'campos_especificos' => [
                    'potencia' => '20',
                    'tipo' => 'LED',
                    'tensao' => '127V',
                    'cor_luz' => 'Branca Fria',
                    'marca' => 'Philips',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Lâmpada LED 40W 220V Branca Quente',
                'categoria' => 'lampadas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 40,
                'quantidade_minima' => 25,
                'valor_unitario' => 18.50,
                'fornecedor' => 'Osram',
                'localizacao_estoque' => 'Prateleira L1',
                'campos_especificos' => [
                    'potencia' => '40',
                    'tipo' => 'LED',
                    'tensao' => '220V',
                    'cor_luz' => 'Branca Quente',
                    'marca' => 'Osram',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Lâmpada LED 60W 127V Branca Fria',
                'categoria' => 'lampadas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 35,
                'quantidade_minima' => 20,
                'valor_unitario' => 22.90,
                'fornecedor' => 'Philips',
                'localizacao_estoque' => 'Prateleira L1',
                'campos_especificos' => [
                    'potencia' => '60',
                    'tipo' => 'LED',
                    'tensao' => '127V',
                    'cor_luz' => 'Branca Fria',
                    'marca' => 'Philips',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Lâmpada Vapor de Sódio 150W 220V',
                'categoria' => 'lampadas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 15,
                'quantidade_minima' => 10,
                'valor_unitario' => 45.00,
                'fornecedor' => 'Osram',
                'localizacao_estoque' => 'Prateleira L1',
                'campos_especificos' => [
                    'potencia' => '150',
                    'tipo' => 'Vapor de Sódio',
                    'tensao' => '220V',
                    'cor_luz' => 'Amarela',
                    'marca' => 'Osram',
                ],
                'ativo' => true,
            ],

            // Reatores
            [
                'nome' => 'Reator Eletrônico 2x40W 127V',
                'categoria' => 'reatores',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 20,
                'quantidade_minima' => 12,
                'valor_unitario' => 35.90,
                'fornecedor' => 'Philips',
                'localizacao_estoque' => 'Prateleira R1',
                'campos_especificos' => [],
                'ativo' => true,
            ],
            [
                'nome' => 'Reator Eletrônico 1x40W 127V',
                'categoria' => 'reatores',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 25,
                'quantidade_minima' => 15,
                'valor_unitario' => 28.50,
                'fornecedor' => 'Osram',
                'localizacao_estoque' => 'Prateleira R1',
                'campos_especificos' => [],
                'ativo' => true,
            ],

            // ========== HIDRÁULICA ==========

            // Tubos PVC
            [
                'nome' => 'Tubo PVC Rígido 20mm Branco',
                'categoria' => 'tubos_pvc',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 200,
                'quantidade_minima' => 100,
                'valor_unitario' => 3.50,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H1',
                'campos_especificos' => [
                    'diametro' => '20',
                    'tipo' => 'Rígido',
                    'cor' => 'Branco',
                    'marca' => 'Tigre',
                    'norma_tecnica' => 'ABNT NBR 5649',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Tubo PVC Rígido 25mm Branco',
                'categoria' => 'tubos_pvc',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 180,
                'quantidade_minima' => 90,
                'valor_unitario' => 4.20,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H1',
                'campos_especificos' => [
                    'diametro' => '25',
                    'tipo' => 'Rígido',
                    'cor' => 'Branco',
                    'marca' => 'Tigre',
                    'norma_tecnica' => 'ABNT NBR 5649',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Tubo PVC Rígido 32mm Branco',
                'categoria' => 'tubos_pvc',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 150,
                'quantidade_minima' => 80,
                'valor_unitario' => 5.80,
                'fornecedor' => 'Amanco',
                'localizacao_estoque' => 'Prateleira H1',
                'campos_especificos' => [
                    'diametro' => '32',
                    'tipo' => 'Rígido',
                    'cor' => 'Branco',
                    'marca' => 'Amanco',
                    'norma_tecnica' => 'ABNT NBR 5649',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Tubo PVC Flexível 20mm Cinza',
                'categoria' => 'tubos_pvc',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 120,
                'quantidade_minima' => 60,
                'valor_unitario' => 4.50,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H1',
                'campos_especificos' => [
                    'diametro' => '20',
                    'tipo' => 'Flexível',
                    'cor' => 'Cinza',
                    'marca' => 'Tigre',
                    'norma_tecnica' => 'ABNT NBR 5649',
                ],
                'ativo' => true,
            ],

            // Conexões Hidráulicas
            [
                'nome' => 'Conexão Tê PVC 20mm',
                'categoria' => 'conexoes_hidraulicas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 50,
                'quantidade_minima' => 30,
                'valor_unitario' => 2.90,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H2',
                'campos_especificos' => [
                    'tipo' => 'Tê',
                    'diametro' => '20',
                    'material' => 'PVC',
                    'marca' => 'Tigre',
                    'norma_tecnica' => 'ABNT NBR',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Conexão Joelho PVC 25mm',
                'categoria' => 'conexoes_hidraulicas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 45,
                'quantidade_minima' => 25,
                'valor_unitario' => 2.50,
                'fornecedor' => 'Amanco',
                'localizacao_estoque' => 'Prateleira H2',
                'campos_especificos' => [
                    'tipo' => 'Joelho',
                    'diametro' => '25',
                    'material' => 'PVC',
                    'marca' => 'Amanco',
                    'norma_tecnica' => 'ABNT NBR',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Conexão Redução PVC 32/25mm',
                'categoria' => 'conexoes_hidraulicas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 30,
                'quantidade_minima' => 20,
                'valor_unitario' => 3.20,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H2',
                'campos_especificos' => [
                    'tipo' => 'Redução',
                    'diametro' => '32/25',
                    'material' => 'PVC',
                    'marca' => 'Tigre',
                    'norma_tecnica' => 'ABNT NBR',
                ],
                'ativo' => true,
            ],

            // Válvulas
            [
                'nome' => 'Válvula Gaveta PVC 25mm',
                'categoria' => 'valvulas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 20,
                'quantidade_minima' => 12,
                'valor_unitario' => 18.90,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H3',
                'campos_especificos' => [
                    'tipo' => 'Gaveta',
                    'diametro' => '25',
                    'material' => 'PVC',
                    'marca' => 'Tigre',
                    'modelo' => 'VG-25',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Válvula Esfera PVC 32mm',
                'categoria' => 'valvulas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 15,
                'quantidade_minima' => 10,
                'valor_unitario' => 25.50,
                'fornecedor' => 'Amanco',
                'localizacao_estoque' => 'Prateleira H3',
                'campos_especificos' => [
                    'tipo' => 'Esfera',
                    'diametro' => '32',
                    'material' => 'PVC',
                    'marca' => 'Amanco',
                    'modelo' => 'VE-32',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Válvula Retenção PVC 25mm',
                'categoria' => 'valvulas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 12,
                'quantidade_minima' => 8,
                'valor_unitario' => 22.90,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H3',
                'campos_especificos' => [
                    'tipo' => 'Retenção',
                    'diametro' => '25',
                    'material' => 'PVC',
                    'marca' => 'Tigre',
                    'modelo' => 'VR-25',
                ],
                'ativo' => true,
            ],

            // Registros
            [
                'nome' => 'Registro Gaveta PVC 20mm',
                'categoria' => 'registros',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 30,
                'quantidade_minima' => 20,
                'valor_unitario' => 8.90,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H4',
                'campos_especificos' => [
                    'tipo' => 'Gaveta',
                    'diametro' => '20',
                    'material' => 'PVC',
                    'marca' => 'Tigre',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Registro Esfera PVC 25mm',
                'categoria' => 'registros',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 25,
                'quantidade_minima' => 15,
                'valor_unitario' => 12.50,
                'fornecedor' => 'Amanco',
                'localizacao_estoque' => 'Prateleira H4',
                'campos_especificos' => [
                    'tipo' => 'Esfera',
                    'diametro' => '25',
                    'material' => 'PVC',
                    'marca' => 'Amanco',
                ],
                'ativo' => true,
            ],

            // Canos
            [
                'nome' => 'Cano PVC 50mm 6 metros',
                'categoria' => 'canos',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 40,
                'quantidade_minima' => 25,
                'valor_unitario' => 28.90,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H5',
                'campos_especificos' => [],
                'ativo' => true,
            ],
            [
                'nome' => 'Cano PVC 75mm 6 metros',
                'categoria' => 'canos',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 30,
                'quantidade_minima' => 20,
                'valor_unitario' => 45.90,
                'fornecedor' => 'Amanco',
                'localizacao_estoque' => 'Prateleira H5',
                'campos_especificos' => [],
                'ativo' => true,
            ],

            // Conexões (genérico)
            [
                'nome' => 'Conexão PVC 20mm',
                'categoria' => 'conexoes',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 100,
                'quantidade_minima' => 50,
                'valor_unitario' => 1.90,
                'fornecedor' => 'Tigre',
                'localizacao_estoque' => 'Prateleira H6',
                'campos_especificos' => [],
                'ativo' => true,
            ],

            // Bombas Poço Artesiano
            [
                'nome' => 'Bomba Submersa 1.5 CV 220V',
                'categoria' => 'bomba_poco_artesiano',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 3,
                'quantidade_minima' => 2,
                'valor_unitario' => 1250.00,
                'fornecedor' => 'KSB Brasil',
                'localizacao_estoque' => 'Almoxarifado Principal',
                'campos_especificos' => [
                    'potencia' => '1.5',
                    'vazao' => '5.0',
                    'pressao' => '30',
                    'tensao' => '220V',
                    'profundidade_maxima' => '50',
                    'marca' => 'KSB',
                    'modelo' => 'KSB-1500',
                    'garantia' => '12',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Bomba Submersa 2.0 CV 220V',
                'categoria' => 'bomba_poco_artesiano',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 2,
                'quantidade_minima' => 1,
                'valor_unitario' => 1850.00,
                'fornecedor' => 'Schneider Electric',
                'localizacao_estoque' => 'Almoxarifado Principal',
                'campos_especificos' => [
                    'potencia' => '2.0',
                    'vazao' => '8.0',
                    'pressao' => '40',
                    'tensao' => '220V',
                    'profundidade_maxima' => '60',
                    'marca' => 'Schneider',
                    'modelo' => 'SCH-2000',
                    'garantia' => '12',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Bomba Submersa 3.0 CV 220V',
                'categoria' => 'bomba_poco_artesiano',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 2,
                'quantidade_minima' => 1,
                'valor_unitario' => 2450.00,
                'fornecedor' => 'KSB Brasil',
                'localizacao_estoque' => 'Almoxarifado Principal',
                'campos_especificos' => [
                    'potencia' => '3.0',
                    'vazao' => '12.0',
                    'pressao' => '50',
                    'tensao' => '220V',
                    'profundidade_maxima' => '80',
                    'marca' => 'KSB',
                    'modelo' => 'KSB-3000',
                    'garantia' => '12',
                ],
                'ativo' => true,
            ],

            // Peças para Poços
            [
                'nome' => 'Mangueira Poço Artesiano 1" 50 metros',
                'categoria' => 'pecas_pocos',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 5,
                'quantidade_minima' => 3,
                'valor_unitario' => 180.00,
                'fornecedor' => 'KSB Brasil',
                'localizacao_estoque' => 'Almoxarifado Principal',
                'campos_especificos' => [],
                'ativo' => true,
            ],
            [
                'nome' => 'Cabo Elétrico Submerso 2.5mm² 50m',
                'categoria' => 'pecas_pocos',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 4,
                'quantidade_minima' => 2,
                'valor_unitario' => 95.00,
                'fornecedor' => 'Prysmian',
                'localizacao_estoque' => 'Almoxarifado Principal',
                'campos_especificos' => [],
                'ativo' => true,
            ],

            // ========== MÁQUINAS E EQUIPAMENTOS ==========

            // Peças para Trator
            [
                'nome' => 'Filtro de Óleo Trator John Deere 5055',
                'categoria' => 'pecas_trator',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 8,
                'quantidade_minima' => 5,
                'valor_unitario' => 45.90,
                'fornecedor' => 'John Deere',
                'localizacao_estoque' => 'Prateleira M1',
                'campos_especificos' => [
                    'tipo_peca' => 'Filtro',
                    'marca' => 'John Deere',
                    'modelo' => 'JD-5055',
                    'referencia' => 'REF-JD-5055-OIL',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Correia Alternador Trator Case 580M',
                'categoria' => 'pecas_trator',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 6,
                'quantidade_minima' => 4,
                'valor_unitario' => 35.50,
                'fornecedor' => 'Case',
                'localizacao_estoque' => 'Prateleira M1',
                'campos_especificos' => [
                    'tipo_peca' => 'Correia',
                    'marca' => 'Case',
                    'modelo' => '580M',
                    'referencia' => 'REF-CASE-580M-ALT',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Mangueira Hidráulica Trator New Holland',
                'categoria' => 'pecas_trator',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 10,
                'quantidade_minima' => 6,
                'valor_unitario' => 85.00,
                'fornecedor' => 'New Holland',
                'localizacao_estoque' => 'Prateleira M1',
                'campos_especificos' => [
                    'tipo_peca' => 'Mangueira',
                    'marca' => 'New Holland',
                    'modelo' => 'NH-75',
                    'referencia' => 'REF-NH-75-HID',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Embreagem Trator John Deere 5055',
                'categoria' => 'pecas_trator',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 2,
                'quantidade_minima' => 1,
                'valor_unitario' => 450.00,
                'fornecedor' => 'John Deere',
                'localizacao_estoque' => 'Prateleira M1',
                'campos_especificos' => [
                    'tipo_peca' => 'Embreagem',
                    'marca' => 'John Deere',
                    'modelo' => 'JD-5055',
                    'referencia' => 'REF-JD-5055-EMB',
                ],
                'ativo' => true,
            ],

            // Peças para Retroescavadeira
            [
                'nome' => 'Filtro de Óleo Retroescavadeira Case 580M',
                'categoria' => 'pecas_retroescavadeira',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 6,
                'quantidade_minima' => 4,
                'valor_unitario' => 52.90,
                'fornecedor' => 'Case',
                'localizacao_estoque' => 'Prateleira M2',
                'campos_especificos' => [
                    'tipo_peca' => 'Filtro',
                    'marca' => 'Case',
                    'modelo' => '580M',
                    'referencia' => 'REF-CASE-580M-OIL',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Balancim Retroescavadeira Case 580M',
                'categoria' => 'pecas_retroescavadeira',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 3,
                'quantidade_minima' => 2,
                'valor_unitario' => 280.00,
                'fornecedor' => 'Case',
                'localizacao_estoque' => 'Prateleira M2',
                'campos_especificos' => [
                    'tipo_peca' => 'Balancim',
                    'marca' => 'Case',
                    'modelo' => '580M',
                    'referencia' => 'REF-CASE-580M-BAL',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Mangueira Hidráulica Retroescavadeira JCB 3CX',
                'categoria' => 'pecas_retroescavadeira',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 8,
                'quantidade_minima' => 5,
                'valor_unitario' => 95.00,
                'fornecedor' => 'JCB',
                'localizacao_estoque' => 'Prateleira M2',
                'campos_especificos' => [
                    'tipo_peca' => 'Mangueira',
                    'marca' => 'JCB',
                    'modelo' => '3CX',
                    'referencia' => 'REF-JCB-3CX-HID',
                ],
                'ativo' => true,
            ],

            // Peças para Caçamba
            [
                'nome' => 'Filtro de Óleo Caçamba Caterpillar 416F',
                'categoria' => 'pecas_cacamba',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 5,
                'quantidade_minima' => 3,
                'valor_unitario' => 68.90,
                'fornecedor' => 'Caterpillar',
                'localizacao_estoque' => 'Prateleira M3',
                'campos_especificos' => [
                    'tipo_peca' => 'Filtro',
                    'marca' => 'Caterpillar',
                    'modelo' => '416F',
                    'referencia' => 'REF-CAT-416F-OIL',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Cilindro Hidráulico Caçamba Volvo EC140',
                'categoria' => 'pecas_cacamba',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 2,
                'quantidade_minima' => 1,
                'valor_unitario' => 1250.00,
                'fornecedor' => 'Volvo',
                'localizacao_estoque' => 'Prateleira M3',
                'campos_especificos' => [
                    'tipo_peca' => 'Cilindro',
                    'marca' => 'Volvo',
                    'modelo' => 'EC140',
                    'referencia' => 'REF-VOLVO-EC140-CIL',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Mangueira Hidráulica Caçamba Komatsu PC200',
                'categoria' => 'pecas_cacamba',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 6,
                'quantidade_minima' => 4,
                'valor_unitario' => 120.00,
                'fornecedor' => 'Komatsu',
                'localizacao_estoque' => 'Prateleira M3',
                'campos_especificos' => [
                    'tipo_peca' => 'Mangueira',
                    'marca' => 'Komatsu',
                    'modelo' => 'PC200',
                    'referencia' => 'REF-KOM-PC200-HID',
                ],
                'ativo' => true,
            ],

            // Peças para Máquinas (genérico)
            [
                'nome' => 'Filtro de Ar Máquinas Pesadas',
                'categoria' => 'pecas_maquinas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 15,
                'quantidade_minima' => 10,
                'valor_unitario' => 35.90,
                'fornecedor' => 'Fleetguard',
                'localizacao_estoque' => 'Prateleira M4',
                'campos_especificos' => [
                    'tipo_maquina' => 'Máquinas Pesadas',
                    'tipo_peca' => 'Filtro de Ar',
                    'marca' => 'Fleetguard',
                    'modelo' => 'FA-1000',
                ],
                'ativo' => true,
            ],

            // Filtros de Óleo
            [
                'nome' => 'Filtro de Óleo Trator 15W-40',
                'categoria' => 'filtros_oleo',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 20,
                'quantidade_minima' => 12,
                'valor_unitario' => 42.90,
                'fornecedor' => 'Fleetguard',
                'localizacao_estoque' => 'Prateleira F2',
                'campos_especificos' => [
                    'tipo_maquina' => 'Trator',
                    'marca' => 'Fleetguard',
                    'modelo' => 'LF-3000',
                    'referencia' => 'REF-FLG-LF3000',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Filtro de Óleo Retroescavadeira',
                'categoria' => 'filtros_oleo',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 15,
                'quantidade_minima' => 10,
                'valor_unitario' => 48.50,
                'fornecedor' => 'Mann',
                'localizacao_estoque' => 'Prateleira F2',
                'campos_especificos' => [
                    'tipo_maquina' => 'Retroescavadeira',
                    'marca' => 'Mann',
                    'modelo' => 'HU-718',
                    'referencia' => 'REF-MANN-HU718',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Filtro de Óleo Caçamba',
                'categoria' => 'filtros_oleo',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 12,
                'quantidade_minima' => 8,
                'valor_unitario' => 55.90,
                'fornecedor' => 'Fleetguard',
                'localizacao_estoque' => 'Prateleira F2',
                'campos_especificos' => [
                    'tipo_maquina' => 'Caçamba',
                    'marca' => 'Fleetguard',
                    'modelo' => 'LF-4000',
                    'referencia' => 'REF-FLG-LF4000',
                ],
                'ativo' => true,
            ],

            // Filtros de Combustível
            [
                'nome' => 'Filtro de Combustível Trator',
                'categoria' => 'filtros_combustivel',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 18,
                'quantidade_minima' => 12,
                'valor_unitario' => 28.90,
                'fornecedor' => 'Fleetguard',
                'localizacao_estoque' => 'Prateleira F3',
                'campos_especificos' => [
                    'tipo_maquina' => 'Trator',
                    'marca' => 'Fleetguard',
                    'modelo' => 'FF-2000',
                    'referencia' => 'REF-FLG-FF2000',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Filtro de Combustível Retroescavadeira',
                'categoria' => 'filtros_combustivel',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 15,
                'quantidade_minima' => 10,
                'valor_unitario' => 32.50,
                'fornecedor' => 'Mann',
                'localizacao_estoque' => 'Prateleira F3',
                'campos_especificos' => [
                    'tipo_maquina' => 'Retroescavadeira',
                    'marca' => 'Mann',
                    'modelo' => 'WK-842',
                    'referencia' => 'REF-MANN-WK842',
                ],
                'ativo' => true,
            ],

            // Pneus
            [
                'nome' => 'Pneu Trator 14.9-28',
                'categoria' => 'pneus',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 4,
                'quantidade_minima' => 2,
                'valor_unitario' => 850.00,
                'fornecedor' => 'Michelin',
                'localizacao_estoque' => 'Almoxarifado Principal',
                'campos_especificos' => [
                    'tipo_veiculo' => 'Trator',
                    'medida' => '14.9-28',
                    'marca' => 'Michelin',
                    'modelo' => 'XM-27',
                    'indice_carga' => '120',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Pneu Trator 18.4-34',
                'categoria' => 'pneus',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 3,
                'quantidade_minima' => 2,
                'valor_unitario' => 1250.00,
                'fornecedor' => 'Bridgestone',
                'localizacao_estoque' => 'Almoxarifado Principal',
                'campos_especificos' => [
                    'tipo_veiculo' => 'Trator',
                    'medida' => '18.4-34',
                    'marca' => 'Bridgestone',
                    'modelo' => 'R-1',
                    'indice_carga' => '140',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Pneu Retroescavadeira 11.00-20',
                'categoria' => 'pneus',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 4,
                'quantidade_minima' => 2,
                'valor_unitario' => 680.00,
                'fornecedor' => 'Pirelli',
                'localizacao_estoque' => 'Almoxarifado Principal',
                'campos_especificos' => [
                    'tipo_veiculo' => 'Retroescavadeira',
                    'medida' => '11.00-20',
                    'marca' => 'Pirelli',
                    'modelo' => 'P-20',
                    'indice_carga' => '120',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Pneu Caçamba 17.5-25',
                'categoria' => 'pneus',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 3,
                'quantidade_minima' => 2,
                'valor_unitario' => 1850.00,
                'fornecedor' => 'Michelin',
                'localizacao_estoque' => 'Almoxarifado Principal',
                'campos_especificos' => [
                    'tipo_veiculo' => 'Caçamba',
                    'medida' => '17.5-25',
                    'marca' => 'Michelin',
                    'modelo' => 'XM-25',
                    'indice_carga' => '140',
                ],
                'ativo' => true,
            ],

            // Baterias
            [
                'nome' => 'Bateria Trator 12V 60Ah',
                'categoria' => 'baterias',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 6,
                'quantidade_minima' => 4,
                'valor_unitario' => 280.00,
                'fornecedor' => 'Moura',
                'localizacao_estoque' => 'Prateleira B1',
                'campos_especificos' => [
                    'tipo_veiculo' => 'Trator',
                    'tensao' => '12V',
                    'amperagem' => '60',
                    'marca' => 'Moura',
                    'modelo' => 'M60',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Bateria Trator 12V 80Ah',
                'categoria' => 'baterias',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 5,
                'quantidade_minima' => 3,
                'valor_unitario' => 350.00,
                'fornecedor' => 'Heliar',
                'localizacao_estoque' => 'Prateleira B1',
                'campos_especificos' => [
                    'tipo_veiculo' => 'Trator',
                    'tensao' => '12V',
                    'amperagem' => '80',
                    'marca' => 'Heliar',
                    'modelo' => 'H80',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Bateria Retroescavadeira 12V 100Ah',
                'categoria' => 'baterias',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 4,
                'quantidade_minima' => 3,
                'valor_unitario' => 420.00,
                'fornecedor' => 'Moura',
                'localizacao_estoque' => 'Prateleira B1',
                'campos_especificos' => [
                    'tipo_veiculo' => 'Retroescavadeira',
                    'tensao' => '12V',
                    'amperagem' => '100',
                    'marca' => 'Moura',
                    'modelo' => 'M100',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Bateria Caçamba 24V 120Ah',
                'categoria' => 'baterias',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 3,
                'quantidade_minima' => 2,
                'valor_unitario' => 580.00,
                'fornecedor' => 'Heliar',
                'localizacao_estoque' => 'Prateleira B1',
                'campos_especificos' => [
                    'tipo_veiculo' => 'Caçamba',
                    'tensao' => '24V',
                    'amperagem' => '120',
                    'marca' => 'Heliar',
                    'modelo' => 'H120',
                ],
                'ativo' => true,
            ],

            // ========== LUBRIFICANTES ==========

            // Óleo de Motor
            [
                'nome' => 'Óleo de Motor 15W-40 API CI-4',
                'categoria' => 'oleo_motor',
                'unidade_medida' => 'litro',
                'quantidade_estoque' => 120,
                'quantidade_minima' => 60,
                'valor_unitario' => 18.90,
                'fornecedor' => 'Shell',
                'localizacao_estoque' => 'Prateleira LUB1',
                'campos_especificos' => [
                    'tipo_maquina' => 'Trator, Retroescavadeira, Caçamba',
                    'viscosidade' => '15W-40',
                    'marca' => 'Shell',
                    'especificacao' => 'API CI-4',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Óleo de Motor 20W-50 API CF-4',
                'categoria' => 'oleo_motor',
                'unidade_medida' => 'litro',
                'quantidade_estoque' => 100,
                'quantidade_minima' => 50,
                'valor_unitario' => 16.50,
                'fornecedor' => 'Mobil',
                'localizacao_estoque' => 'Prateleira LUB1',
                'campos_especificos' => [
                    'tipo_maquina' => 'Trator, Retroescavadeira',
                    'viscosidade' => '20W-50',
                    'marca' => 'Mobil',
                    'especificacao' => 'API CF-4',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Óleo de Motor 10W-30 API CJ-4',
                'categoria' => 'oleo_motor',
                'unidade_medida' => 'litro',
                'quantidade_estoque' => 80,
                'quantidade_minima' => 40,
                'valor_unitario' => 22.90,
                'fornecedor' => 'Castrol',
                'localizacao_estoque' => 'Prateleira LUB1',
                'campos_especificos' => [
                    'tipo_maquina' => 'Caçamba, Máquinas Pesadas',
                    'viscosidade' => '10W-30',
                    'marca' => 'Castrol',
                    'especificacao' => 'API CJ-4',
                ],
                'ativo' => true,
            ],

            // Óleo Hidráulico
            [
                'nome' => 'Óleo Hidráulico ISO 46 AW',
                'categoria' => 'oleo_hidraulico',
                'unidade_medida' => 'litro',
                'quantidade_estoque' => 150,
                'quantidade_minima' => 80,
                'valor_unitario' => 24.90,
                'fornecedor' => 'Shell',
                'localizacao_estoque' => 'Prateleira LUB2',
                'campos_especificos' => [
                    'tipo_maquina' => 'Trator, Retroescavadeira, Caçamba',
                    'viscosidade' => 'ISO 46',
                    'marca' => 'Shell',
                    'especificacao' => 'AW 46',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Óleo Hidráulico ISO 68 AW',
                'categoria' => 'oleo_hidraulico',
                'unidade_medida' => 'litro',
                'quantidade_estoque' => 100,
                'quantidade_minima' => 50,
                'valor_unitario' => 26.50,
                'fornecedor' => 'Mobil',
                'localizacao_estoque' => 'Prateleira LUB2',
                'campos_especificos' => [
                    'tipo_maquina' => 'Retroescavadeira, Caçamba',
                    'viscosidade' => 'ISO 68',
                    'marca' => 'Mobil',
                    'especificacao' => 'AW 68',
                ],
                'ativo' => true,
            ],

            // Graxa
            [
                'nome' => 'Graxa EP 2 NLGI 2',
                'categoria' => 'graxa',
                'unidade_medida' => 'kg',
                'quantidade_estoque' => 50,
                'quantidade_minima' => 25,
                'valor_unitario' => 12.90,
                'fornecedor' => 'Shell',
                'localizacao_estoque' => 'Prateleira LUB3',
                'campos_especificos' => [
                    'tipo_maquina' => 'Trator, Retroescavadeira, Caçamba',
                    'viscosidade' => 'NLGI 2',
                    'marca' => 'Shell',
                    'especificacao' => 'EP 2',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Graxa EP 3 NLGI 3',
                'categoria' => 'graxa',
                'unidade_medida' => 'kg',
                'quantidade_estoque' => 40,
                'quantidade_minima' => 20,
                'valor_unitario' => 14.50,
                'fornecedor' => 'Mobil',
                'localizacao_estoque' => 'Prateleira LUB3',
                'campos_especificos' => [
                    'tipo_maquina' => 'Máquinas Pesadas',
                    'viscosidade' => 'NLGI 3',
                    'marca' => 'Mobil',
                    'especificacao' => 'EP 3',
                ],
                'ativo' => true,
            ],

            // Combustível
            [
                'nome' => 'Diesel S10',
                'categoria' => 'combustivel',
                'unidade_medida' => 'litro',
                'quantidade_estoque' => 5000,
                'quantidade_minima' => 2000,
                'valor_unitario' => 5.89,
                'fornecedor' => 'Petrobras',
                'localizacao_estoque' => 'Tanque Principal',
                'campos_especificos' => [],
                'ativo' => true,
            ],
            [
                'nome' => 'Gasolina Comum',
                'categoria' => 'combustivel',
                'unidade_medida' => 'litro',
                'quantidade_estoque' => 2000,
                'quantidade_minima' => 1000,
                'valor_unitario' => 5.45,
                'fornecedor' => 'Petrobras',
                'localizacao_estoque' => 'Tanque Secundário',
                'campos_especificos' => [],
                'ativo' => true,
            ],

            // ========== SEGURANÇA E EPI ==========

            // Roupa Eletricista
            [
                'nome' => 'Bota de Segurança Eletricista NR-10',
                'categoria' => 'roupa_eletricista',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 15,
                'quantidade_minima' => 10,
                'valor_unitario' => 89.90,
                'fornecedor' => 'DuPont',
                'localizacao_estoque' => 'Prateleira EPI-A',
                'campos_especificos' => [
                    'tipo' => 'Bota',
                    'tamanho' => '39/40',
                    'cor' => 'Laranja',
                    'material' => 'Couro sintético',
                    'norma_tecnica' => 'NR-10',
                    'certificacao' => 'INMETRO',
                    'marca' => 'DuPont',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Bota de Segurança Eletricista NR-10 Tamanho 41/42',
                'categoria' => 'roupa_eletricista',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 12,
                'quantidade_minima' => 8,
                'valor_unitario' => 89.90,
                'fornecedor' => 'DuPont',
                'localizacao_estoque' => 'Prateleira EPI-A',
                'campos_especificos' => [
                    'tipo' => 'Bota',
                    'tamanho' => '41/42',
                    'cor' => 'Laranja',
                    'material' => 'Couro sintético',
                    'norma_tecnica' => 'NR-10',
                    'certificacao' => 'INMETRO',
                    'marca' => 'DuPont',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Blusão Eletricista NR-10',
                'categoria' => 'roupa_eletricista',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 12,
                'quantidade_minima' => 8,
                'valor_unitario' => 125.00,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira EPI-A',
                'campos_especificos' => [
                    'tipo' => 'Blusão',
                    'tamanho' => 'G',
                    'cor' => 'Azul',
                    'material' => 'Algodão/Poliéster',
                    'norma_tecnica' => 'NR-10',
                    'certificacao' => 'INMETRO',
                    'marca' => '3M',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Calça Eletricista NR-10',
                'categoria' => 'roupa_eletricista',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 12,
                'quantidade_minima' => 8,
                'valor_unitario' => 95.00,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira EPI-A',
                'campos_especificos' => [
                    'tipo' => 'Calça',
                    'tamanho' => 'G',
                    'cor' => 'Azul',
                    'material' => 'Algodão/Poliéster',
                    'norma_tecnica' => 'NR-10',
                    'certificacao' => 'INMETRO',
                    'marca' => '3M',
                ],
                'ativo' => true,
            ],

            // EPIs
            [
                'nome' => 'Capacete de Segurança Classe A',
                'categoria' => 'epi',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 20,
                'quantidade_minima' => 15,
                'valor_unitario' => 45.00,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira EPI-B',
                'campos_especificos' => [
                    'tipo' => 'Capacete',
                    'ca' => 'CA-12345',
                    'tamanho' => 'Único',
                    'norma_tecnica' => 'ABNT NBR 8221',
                    'validade' => '12',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Óculos de Proteção UV',
                'categoria' => 'epi',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 25,
                'quantidade_minima' => 20,
                'valor_unitario' => 28.90,
                'fornecedor' => 'DuPont',
                'localizacao_estoque' => 'Prateleira EPI-B',
                'campos_especificos' => [
                    'tipo' => 'Óculos',
                    'ca' => 'CA-67890',
                    'tamanho' => 'Único',
                    'norma_tecnica' => 'ABNT NBR 12345',
                    'validade' => '12',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Luvas de Proteção Elétrica Classe 00',
                'categoria' => 'epi',
                'unidade_medida' => 'par',
                'quantidade_estoque' => 30,
                'quantidade_minima' => 20,
                'valor_unitario' => 35.90,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira EPI-B',
                'campos_especificos' => [
                    'tipo' => 'Luvas',
                    'ca' => 'CA-11111',
                    'tamanho' => 'M',
                    'norma_tecnica' => 'NR-10',
                    'validade' => '6',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Protetor Auricular',
                'categoria' => 'epi',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 20,
                'quantidade_minima' => 15,
                'valor_unitario' => 22.50,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira EPI-B',
                'campos_especificos' => [
                    'tipo' => 'Protetor Auricular',
                    'ca' => 'CA-22222',
                    'tamanho' => 'Único',
                    'norma_tecnica' => 'ABNT NBR',
                    'validade' => '12',
                ],
                'ativo' => true,
            ],

            // Equipamentos de Segurança
            [
                'nome' => 'Cone de Sinalização 50cm',
                'categoria' => 'equipamentos_seguranca',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 30,
                'quantidade_minima' => 20,
                'valor_unitario' => 18.90,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira S1',
                'campos_especificos' => [
                    'tipo' => 'Cone',
                    'norma_tecnica' => 'ABNT NBR',
                    'certificacao' => 'INMETRO',
                    'marca' => '3M',
                    'validade' => '24',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Fita de Sinalização Refletiva',
                'categoria' => 'equipamentos_seguranca',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 200,
                'quantidade_minima' => 100,
                'valor_unitario' => 2.50,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira S1',
                'campos_especificos' => [
                    'tipo' => 'Fita',
                    'norma_tecnica' => 'ABNT NBR',
                    'certificacao' => 'INMETRO',
                    'marca' => '3M',
                    'validade' => '24',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Barreira de Segurança Portátil',
                'categoria' => 'equipamentos_seguranca',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 10,
                'quantidade_minima' => 6,
                'valor_unitario' => 85.00,
                'fornecedor' => 'DuPont',
                'localizacao_estoque' => 'Prateleira S1',
                'campos_especificos' => [
                    'tipo' => 'Barreira',
                    'norma_tecnica' => 'ABNT NBR',
                    'certificacao' => 'INMETRO',
                    'marca' => 'DuPont',
                    'validade' => '36',
                ],
                'ativo' => true,
            ],

            // Sinalização
            [
                'nome' => 'Placa de Sinalização Obra em Andamento',
                'categoria' => 'sinalizacao',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 15,
                'quantidade_minima' => 10,
                'valor_unitario' => 35.90,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira S2',
                'campos_especificos' => [
                    'tipo' => 'Placa',
                    'tamanho' => '30x40cm',
                    'material' => 'Refletivo',
                    'cor' => 'Amarelo',
                    'refletivo' => 'Sim',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Placa de Sinalização Perigo Alta Tensão',
                'categoria' => 'sinalizacao',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 12,
                'quantidade_minima' => 8,
                'valor_unitario' => 42.50,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira S2',
                'campos_especificos' => [
                    'tipo' => 'Placa',
                    'tamanho' => '30x40cm',
                    'material' => 'Refletivo',
                    'cor' => 'Vermelho',
                    'refletivo' => 'Sim',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Cone de Sinalização Refletivo 70cm',
                'categoria' => 'sinalizacao',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 25,
                'quantidade_minima' => 15,
                'valor_unitario' => 28.90,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira S2',
                'campos_especificos' => [
                    'tipo' => 'Cone',
                    'tamanho' => '70cm',
                    'material' => 'Refletivo',
                    'cor' => 'Laranja',
                    'refletivo' => 'Sim',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Fita de Sinalização Amarela Refletiva',
                'categoria' => 'sinalizacao',
                'unidade_medida' => 'metro',
                'quantidade_estoque' => 300,
                'quantidade_minima' => 150,
                'valor_unitario' => 1.90,
                'fornecedor' => '3M',
                'localizacao_estoque' => 'Prateleira S2',
                'campos_especificos' => [
                    'tipo' => 'Fita',
                    'tamanho' => '10cm',
                    'material' => 'Refletivo',
                    'cor' => 'Amarelo',
                    'refletivo' => 'Sim',
                ],
                'ativo' => true,
            ],

            // ========== FERRAMENTAS ==========

            [
                'nome' => 'Furadeira Elétrica 500W 127V',
                'categoria' => 'ferramentas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 5,
                'quantidade_minima' => 3,
                'valor_unitario' => 189.90,
                'fornecedor' => 'Bosch',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'tipo' => 'Furadeira',
                    'marca' => 'Bosch',
                    'modelo' => 'GSR-500',
                    'voltagem' => '127V',
                    'garantia' => '12',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Parafusadeira Elétrica 18V Bateria',
                'categoria' => 'ferramentas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 4,
                'quantidade_minima' => 2,
                'valor_unitario' => 350.00,
                'fornecedor' => 'Makita',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'tipo' => 'Parafusadeira',
                    'marca' => 'Makita',
                    'modelo' => 'DF-18',
                    'voltagem' => 'Bateria',
                    'garantia' => '12',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Alicate Universal 8"',
                'categoria' => 'ferramentas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 10,
                'quantidade_minima' => 6,
                'valor_unitario' => 28.90,
                'fornecedor' => 'Vonder',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'tipo' => 'Alicate',
                    'marca' => 'Vonder',
                    'modelo' => 'AL-8',
                    'voltagem' => 'N/A',
                    'garantia' => '6',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Chave de Fenda Phillips #2',
                'categoria' => 'ferramentas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 15,
                'quantidade_minima' => 10,
                'valor_unitario' => 8.90,
                'fornecedor' => 'Vonder',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'tipo' => 'Chave de Fenda',
                    'marca' => 'Vonder',
                    'modelo' => 'CF-PH2',
                    'voltagem' => 'N/A',
                    'garantia' => '6',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Multímetro Digital',
                'categoria' => 'ferramentas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 3,
                'quantidade_minima' => 2,
                'valor_unitario' => 125.00,
                'fornecedor' => 'Minipa',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'tipo' => 'Multímetro',
                    'marca' => 'Minipa',
                    'modelo' => 'ET-1000',
                    'voltagem' => 'Bateria',
                    'garantia' => '12',
                ],
                'ativo' => true,
            ],
            [
                'nome' => 'Serra Circular 1400W 127V',
                'categoria' => 'ferramentas',
                'unidade_medida' => 'unidade',
                'quantidade_estoque' => 2,
                'quantidade_minima' => 1,
                'valor_unitario' => 450.00,
                'fornecedor' => 'Bosch',
                'localizacao_estoque' => 'Prateleira F1',
                'campos_especificos' => [
                    'tipo' => 'Serra Circular',
                    'marca' => 'Bosch',
                    'modelo' => 'GKS-1400',
                    'voltagem' => '127V',
                    'garantia' => '12',
                ],
                'ativo' => true,
            ],
        ];

        foreach ($materiais as $materialData) {
            // Gerar código automaticamente
            $materialData['codigo'] = Material::generateCode('MAT', $materialData['categoria']);

            // Converter campos_especificos para JSON se for array
            if (isset($materialData['campos_especificos']) && is_array($materialData['campos_especificos'])) {
                $materialData['campos_especificos'] = json_encode($materialData['campos_especificos']);
            }

            Material::create($materialData);
        }

        $this->command->info('✅ Materiais seedados com sucesso!');
        $this->command->info('Total de materiais criados: ' . count($materiais));
    }
}
